name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_main.py
      id: test_main-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 20
        max-score: 100
        setup-command: pip install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_MAIN-PY_RESULTS: "${{steps.test_main-py.outputs.result}}"
      with:
        runners: test_main-py
